---

- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - name: Install Cloud packages
      become: yes
      package:
        state: latest
        name:
          - cloud-init
