---

- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - include_tasks: roles/desktop/common.yaml
    - include_tasks: roles/desktop/i3-xorg.yaml
    - include_tasks: roles/desktop/sway-wayland.yaml
