---

- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - name: Install needed packages
      become: yes
      package:
        state: latest
        name: 
          - sway
          - waybar
          - wofi
          - swaylock
          - mako
          - libappindicator-gtk3
          - ttf-font-awesome
          - gopass
          - alacritty
          - gammastep
          - ranger
          - pulseaudio
    
    - name: Install less needed packages
      become: yes
      package:
        state: latest
        name: 
          - qutebrowser
          - vlc
          - openconnect
          - playerctl
          - remmina
          - freerdp
          - pavucontrol
          - virt-manager
          - eog
          - zathura
          - zathura-pdf-mupdf
    
    - copy:
        src: files/sway
        dest: ~/.config/
    
    - copy:
        src: files/waybar
        dest: ~/.config/
    - shell: chmod +x ~/.config/waybar/waybar.sh
    - shell: chmod +x ~/.config/waybar/modules/*
    
    - copy:
        src: files/swaylock
        dest: ~/.config/
    
    - copy:
        src: files/mako
        dest: ~/.config/
    
    - copy:
        src: files/bash_profile_sway
        dest: ~/.bash_profile
    
    - file: path=~/img state=directory
    - get_url: url=https://public.epheo.eu/wallpaper.jpg dest=~/img/
    
    - copy:
        src: files/qutebrowser
        dest: ~/.config/
    
    - copy:
        src: files/gtk-2.0
        dest: ~/.config/
    
    - copy:
        src: files/gtk-3.0
        dest: ~/.config/
    
    - copy:
        src: files/gammastep
        dest: ~/.config/
    
    - copy:
        src: files/Code
        dest: ~/.config/
    
    - copy:
        src: files/Code
        dest: "~/.config/Code - OSS/"
    
    - name: Reload sway config
      ignore_errors: yes
      shell: swaymsg reload
