---

- hosts: nodes
  gather_facts: no
  roles:
    - common
    - desktop
  tasks:
    - include_tasks: roles/common/tasks/install_base_pkgs.yaml
    - include_tasks: roles/desktop/tasks/install_common.yaml
    - include_tasks: roles/desktop/tasks/install_sway_wayland.yaml
