---

- name: Install needed packages
  become: yes
  package:
    state: latest
    name: 
      - ttf-font-awesome
      - gopass
      - alacritty
      - gammastep
      - ranger
      - pulseaudio
      - materia-gtk-theme
      - papirus-icon-theme
  tags: [ xorg, wayland ]

- name: Install less needed packages
  become: yes
  package:
    state: latest
    name: 
      - qutebrowser
      - vlc
      - openconnect
      - playerctl
      - remmina
      - freerdp
      - pavucontrol
      - virt-manager
      - eog
      - zathura
      - zathura-pdf-mupdf
      - libappindicator-gtk3
  tags: [ xorg, wayland ]

- file: path=~/img state=directory
  tags: [ xorg, wayland ]
- get_url: url=https://public.epheo.eu/wallpaper.jpg dest=~/img/
  tags: [ xorg, wayland ]

- copy:
    src: dotfiles/qutebrowser
    dest: ~/.config/
  tags: [ xorg, wayland ]

- copy:
    src: dotfiles/gtk-2.0
    dest: ~/.config/
  tags: [ xorg, wayland ]

- copy:
    src: dotfiles/gtk-3.0
    dest: ~/.config/
  tags: [ xorg, wayland ]

