---

- name: Install needed packages
  become: yes
  package:
    state: latest
    name: 
      - i3
      - i3blocks
      - xorg-xinit
      - xorg
      - numlockx


- copy:
    src: files/xorg/Xdefaults
    dest: ~/.Xdefaults

- copy:
    src: files/xorg/xinitrc
    dest: ~/.xinitrc

- file: path=~/.config/i3blocks state=directory
- copy:
    src: files/xorg/i3/i3blocks.conf
    dest: ~/.config/i3blocks/config

- copy:
    src: files/xorg/i3/config
    dest: ~/.config/i3/config

- name: Reload i3 config
  ignore_errors: yes
  shell: i3-msg reload
