---

- name: Install needed packages
  become: yes
  package:
    state: latest
    name: 
      - sway
      - waybar
      - wofi
      - swaylock
      - mako
  tags: [ sway, wayland ]

- copy:
    src: dotfiles/wayland/sway
    dest: ~/.config/
  tags: [ sway, wayland ]

- copy:
    src: dotfiles/wayland/waybar
    dest: ~/.config/
  tags: [ sway, wayland, waybar ]
- shell: chmod +x ~/.config/waybar/waybar.sh
  tags: [ sway, wayland, waybar ]
- shell: chmod +x ~/.config/waybar/modules/*
  tags: [ sway, wayland, waybar ]

- copy:
    src: dotfiles/wayland/swaylock
    dest: ~/.config/
  tags: [ sway, wayland ]

- copy:
    src: dotfiles/wayland/mako
    dest: ~/.config/
  tags: [ sway, wayland ]

- copy:
    src: dotfiles/wayland/bash_profile_sway
    dest: ~/.bash_profile
  tags: [ sway, wayland ]

- name: Reload sway config
  ignore_errors: yes
  shell: swaymsg reload
  tags: [ sway, wayland ]

