---

- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:

    - name: Install Cloud packages
      tags: cloud
      become: yes
      package:
        state: latest
        name:
          - cloud-init

