---

- debug:
    var: "{{ ansible_distribution }}"

- name: Yum clean all
  become: yes
  shell: |
    yum clean all
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Upgrade all packages
  become: yes
  package:
    name: "*"
    state: latest
  when: ansible_distribution != 'Archlinux'

- name: Upgrade all packages
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == 'Archlinux'

- include_tasks: reboot.yaml
  when: allow_reboot is sameas true

