#!/bin/bash
# DEFMS: Distro Enhancer for maybe something

debug=no
interactive=no

# Guest image personality
cloud=yes
desktop=yes
rescue=no

# Guest boot mode can be uefi or bios
boot_mode=uefi

# Constructing file name
date=$(date -Iseconds |sed -r 's/[^a-za-z0-9]//g; s/0000/0/g')
personality=$(if [ $cloud = yes ] ;then echo 'cloud-' ;fi)
personality=${personality}$(if [ $rescue = yes ] ;then echo 'rescue-' ;fi)
personality=${personality}$(if [ $desktop = yes ] ;then echo 'desktop-' ;fi)

file_name=arch-${boot_mode}-${personality}${date}-x86_64

directory=/mnt/data/build

# Authentication
user=cloud
password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c6)
root_password=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c6)

# Destination format can be qcow2 or raw
format=qcow2

# Volume size in Gb
disk_size=8

